### ISSUE TITLE
Add a submission form to the Research Mapping page 

### ISSUE THREAD

**Issue by NyssrineA** [AmericanRedCross/research-mapping#16]
Hi @danbjoseph

As discussed, 

- [x] I have created a google form, I've shared it with your Gmail account.

- [x] Can you please add it to the Research Map landing page by the end of this week? 

Thank you,

**Comment by danbjoseph** [comment]
How do you want the link added? Just a sentence at the end of the opening text?

<img width="998" alt="Screen Shot 2021-05-05 at 10 32 11 AM" src="https://user-images.githubusercontent.com/4806884/117158142-28b6e180-ad8d-11eb-8f96-6dabeb8ebf2a.png">


-------

Also, maybe add a contact email to the form description?
<img width="898" alt="Screen Shot 2021-05-05 at 10 33 24 AM" src="https://user-images.githubusercontent.com/4806884/117158348-53a13580-ad8d-11eb-9e90-adc22873c0d5.png">

**Comment by NyssrineA** [comment]
Thanks, @danbjoseph for adding the contact form. when someone clicks on the "share your research" can you make it open in another tab please?
